[project]
name = "practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sixfunny", email = "example@email.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ninja>=1.13.2",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
]

[project.scripts]
practice = "practice:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
